# Generated by Django 4.2.13 on 2024-05-31 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dostupnost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Odbor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meno', models.CharField(max_length=20)),
                ('priezvisko', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('heslo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ucitel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meno', models.CharField(max_length=20)),
                ('priezvisko', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('heslo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=50)),
                ('popis', models.TextField()),
                ('koznultacie', models.IntegerField()),
                ('dostupnosť', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soc.dostupnost')),
                ('konzultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soc.ucitel')),
                ('odbor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soc.odbor')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='soc.student')),
            ],
        ),
    ]
