# Generated by Django 4.2.13 on 2024-05-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0002_alter_dostupnost_options_alter_odbor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odbor',
            name='nazov',
            field=models.CharField(max_length=100),
        ),
    ]
