# Generated by Django 4.2.9 on 2024-06-11 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soc', '0005_rename_dostupnosť_tema_dostupnost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tema',
            old_name='koznultacie',
            new_name='konzultacie',
        ),
    ]
